services:
  - type: web
    name: hospital-finder
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: KAKAO_JS_API_KEY
        sync: false
      - key: KAKAO_MAP_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: USE_GROQ
        value: "true"
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "gemma2-9b-it"
